### ISSUE TITLE
GeoTiff float (Digitales Höhenmodell Oberfläche NRW)

### ISSUE THREAD

**Issue by pfefferCode** [GeoTIFF/geotiff.io#274]
Hi!

The problem occurs using tiffs like this: https://www.wcs.nrw.de/geobasis/wcs_nw_dom?REQUEST=GetCoverage&SERVICE=WCS&VERSION=2.0.1&COVERAGEID=nw_dom&FORMAT=image/tiff&SUBSET=x(356000,357000)&SUBSET=y(5699000,5700000)&OUTFILE=dom1_32_356_5699_1_nw_2020&APP=timonline

(hint you can pick your own .tiff by: this URL: https://www.tim-online.nrw.de/tim-online2/?bg=basemapDE_grau&scale=1400000&center=450000,5700000&wms=https://www.wms.nrw.de/geobasis/wms_nw_dhm-uebersicht,nw_dhm_metadaten&opacity=70&legend=true (klick on "download" an choose "Höhenmodelle" --> "Digitales Oberflächenmodell" --> "weiter" --> "*.tiff" --> "weiter" --> select one --> "weiter"....)

I tried it on http://app.geotiff.io/

There are two issues that might be connected:

1. Loading the .tif file is working always only at the second try. After the first try the area is marked all in the same gray. After the second loading of the image, correct grey values are shown.
3. Identifying values on http://app.geotiff.io/ does not give a result. In the JavaScript console appears the following error:
```
bundle.js:35 Uncaught TypeError: Cannot read properties of null (reading 'then')
    at r.<anonymous> (bundle.js:35:1059117)
    at r.fire (bundle.js:92:5274)
    at r._fireDOMEvent (bundle.js:92:43297)
    at r._handleDOMEvent (bundle.js:92:42540)
    at HTMLDivElement.a (bundle.js:92:22968)
    at r.<anonymous> (bundle.js:35:1059117)
    at r.fire (bundle.js:92:5274)
    at r._fireDOMEvent (bundle.js:92:43297)
    at r._handleDOMEvent (bundle.js:92:42540)
    at HTMLDivElement.a (bundle.js:92:22968)
(anonymous) @ bundle.js:35
fire @ bundle.js:92
_fireDOMEvent @ bundle.js:92
_handleDOMEvent @ bundle.js:92
a @ bundle.js:92
(anonymous) @ bundle.js:35
fire @ bundle.js:92
_fireDOMEvent @ bundle.js:92
_handleDOMEvent @ bundle.js:92
a @ bundle.js:92

```

Thank you for your work!
   PfefferCode.

PS: I first reported it here: https://github.com/geotiffjs/geotiff.js/issues/419 but I was told, here is the correct place.

**Comment by DanielJDufour** [comment]
Also, would you be interested in submitting this file to https://github.com/geotiff/test-data ?  I don't think we have other test files in the EPSG:25832 projection.  We'll also be able to use it to test the visualization once it's added.

**Comment by pfefferCode** [comment]
@DanielJDufour Thanx for answering and provoding a fix so fast!
How can I test if it works? (When) will it be included in http://app.geotiff.io/ ?

Pleas feel free to add the .tif to the test data.

**Comment by DanielJDufour** [comment]
It should be included in app.geotiff.io right now :-)

Note: the identify function should be working, but the visualization is a work in progress.

**Comment by pfefferCode** [comment]
@DanielJDufour 
Thanx! identifying works now :-)
Showing the values as different grey tones still work only on the second load of the same image.
All other functions (Mean, Sum, Mode, Median, Histogram - did not test Band arithmetic and Raster calculator) do not work.

**Comment by DanielJDufour** [comment]
Okay. I'll fix the other stats now.  Thanks for testing!

**Comment by DanielJDufour** [comment]
Mean, Min, Max, Sum, Mode, and Median should all be fixed now.  Will have to look into Histogram, Band Arithmetic, and Raster Calculator.

**Comment by pfefferCode** [comment]
tested: mean, min, max, sum, mode an median as rectangle and polygon: all deliver plausible values. Thank you.
Histogram does not work till now.
